-- Create class_notes table for storing class notes/announcements
-- This matches your existing schema
CREATE TABLE IF NOT EXISTS class_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id TEXT UNIQUE NOT NULL, -- ID singkat buatan pengguna, contoh: "aturan_kelas"
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    created_by TEXT, -- Menyimpan nama pengirim
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ
);

-- Create index for faster lookups by note_id
CREATE INDEX IF NOT EXISTS idx_class_notes_note_id ON class_notes(note_id);

-- Create index for ordering by created_at
CREATE INDEX IF NOT EXISTS idx_class_notes_created_at ON class_notes(created_at DESC);

-- Insert sample data
INSERT INTO class_notes (note_id, title, content, created_by) VALUES 
('aturan_kelas', 'Aturan Kelas TKJ C', 
'📋 **Aturan Kelas X TKJ C**

1. **Piket Harian**
   - Piket wajib selesai sebelum jam 7:00 WIB
   - Pembagian tugas sesuai jadwal yang telah ditentukan
   - Bertanggung jawab atas kebersihan kelas

2. **Kas Kelas**
   - Kas dibayar setiap hari Senin
   - Nominal: Rp 2.000 per minggu
   - Pembayaran dilakukan kepada bendahara

3. **Kehadiran**
   - Hadir tepat waktu sesuai jadwal
   - Izin/sakit harus ada surat keterangan
   - Absen tanpa keterangan akan mendapat sanksi

4. **Tugas dan PR**
   - Kerjakan tugas tepat waktu
   - Kumpulkan sesuai deadline yang ditentukan
   - Bantu teman yang kesulitan

5. **Sikap dan Perilaku**
   - Saling menghormati sesama teman
   - Menjaga nama baik kelas
   - Aktif dalam kegiatan kelas

Mari kita jaga kebersamaan dan semangat belajar! 🚀'),

('jadwal_piket', 'Jadwal Piket Mingguan', 
'🧹 **Jadwal Piket Kelas X TKJ C**

**Senin:**
- Kelompok 1: Ahmad, Budi, Citra
- Tugas: Sapu, pel, bersihkan papan tulis

**Selasa:**
- Kelompok 2: Dina, Eko, Fani
- Tugas: Sapu, pel, rapikan meja kursi

**Rabu:**
- Kelompok 3: Gita, Hadi, Ina
- Tugas: Sapu, pel, bersihkan jendela

**Kamis:**
- Kelompok 4: Joko, Kiki, Lina
- Tugas: Sapu, pel, buang sampah

**Jumat:**
- Kelompok 5: Maya, Nino, Oki
- Tugas: Sapu, pel, bersihkan papan tulis

**Sabtu:**
- Semua kelompok bergantian
- Bersih-bersih menyeluruh

⏰ **Waktu Piket:** 06:30 - 07:00 WIB
📝 **Catatan:** Jika berhalangan, cari pengganti atau tukar jadwal dengan kelompok lain'),

('info_kas', 'Informasi Kas Kelas', 
'💰 **Informasi Kas Kelas X TKJ C**

**Ketentuan Kas:**
- Nominal: Rp 2.000 per minggu
- Pembayaran: Setiap hari Senin
- Bendahara: [Nama Bendahara]

**Penggunaan Kas:**
1. Pembelian alat kebersihan
2. Snack untuk acara kelas
3. Hadiah lomba/kompetisi
4. Keperluan mendadak kelas

**Cara Pembayaran:**
- Bayar langsung ke bendahara
- Catat di buku kas
- Simpan struk sebagai bukti

**Denda Keterlambatan:**
- Telat 1 minggu: +Rp 500
- Telat 2 minggu: +Rp 1.000
- Telat >2 minggu: +Rp 2.000

**Saldo Kas Saat Ini:** [Update berkala]

Mari kita jaga kas kelas dengan baik untuk kepentingan bersama! 💪')

ON CONFLICT (note_id) DO NOTHING;

-- Add comment to table
COMMENT ON TABLE class_notes IS 'Tabel untuk menyimpan catatan penting kelas.';
COMMENT ON COLUMN class_notes.note_id IS 'ID singkat buatan pengguna, contoh: "aturan_kelas"';
COMMENT ON COLUMN class_notes.title IS 'Judul/subjek catatan';
COMMENT ON COLUMN class_notes.content IS 'Isi lengkap catatan dalam format markdown';
COMMENT ON COLUMN class_notes.created_by IS 'Nama pengirim yang membuat catatan';
COMMENT ON COLUMN class_notes.created_at IS 'Timestamp ketika catatan dibuat';
COMMENT ON COLUMN class_notes.updated_at IS 'Timestamp ketika catatan terakhir diubah';